### ISSUE TITLE
Add unit test for Directory.EnsureExists that creates missing directories

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LANDIS-II-Foundation/Library-Utilities#11]
```
Add unit test for Directory.EnsureExists that actually creates several missing 
directories.
```

Original issue reported on code.google.com by `jdomi...@green-code.com` on 21 Jun 2010 at 10:04

**Comment by rmscheller** [comment]
Is the unit testing framework still valid and up-to-date?  If so, add to the unit tests.  If not, we need to evaluate the effort required to re-launch unit testing.
