### ISSUE TITLE
Change namespace to Landis.Utilities

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LANDIS-II-Foundation/Library-Utilities#3]
```
Change the namespace in the library to "Landis.Utilities" to reflect its
new name, and to use fewer levels than the current namespace.
```

Original issue reported on code.google.com by `jdomi...@green-code.com` on 15 Apr 2010 at 1:10

**Comment by VSchuster** [comment]
Almost every extension references Edu.Wisc.Forest.Flel.Util namespace. Changing the namespace to "Landis.Utilities" This will be a breaking change to rename the namespace. Nearly all of the extensions will need to be updated in some way to reflect this change.

**Comment by rmscheller** [comment]
Vincent, this is an investment in the future.  We will save those updates for all changes going forward.
